//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaiDapWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        [Required(ErrorMessage = "* Required"), Display(Name="ID")]
        public string username { get; set; }
        [Required(ErrorMessage = "* Required"), Display(Name = "Mật khẩu")]
        public string password { get; set; }
        public int id_role { get; set; }
    
        public virtual Role Role { get; set; }
    }


}
