//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaiDapWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Answer
    {
        [Display(Name = "ID")]
        public long id { get; set; }
        [Display(Name = "Loại câu hỏi")]
        public long question_id { get; set; }
        [Required(ErrorMessage = "* Required"), Display(Name = "Nội dung")]
        public string text { get; set; }
        [Display(Name = "Mã GV")]
        public string ministry_id { get; set; }

        public System.DateTime time_respond { get; set; }
    
        public virtual Ministry Ministry { get; set; }
    }
}
