//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaiDapWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Ministry
    {
        public Ministry()
        {
            this.Answers = new HashSet<Answer>();
        }

        [Required(ErrorMessage = "* Required"), Display(Name = "ID")]
        public string ministry_id { get; set; }
        [Required(ErrorMessage = "* Required"), Display(Name = "Họ tên")]
        public string name { get; set; }
        [Required(ErrorMessage = "* Required"), Display(Name = "Ngày sinh")]
        public System.DateTime date_of_birth { get; set; }
        [Required(ErrorMessage = "* Required"), Display(Name = "Địa chỉ")]
        public string address { get; set; }
        [Required(ErrorMessage = "* Required"), Display(Name = "Giới tính")]
        public bool sex { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
    }
}
